# consulta-multi-tabelas.sql
USE EMPRESA;

SELECT NOME, SALARIO FROM FUNCIONARIOS;

SELECT FUNCIONARIOS.NOME, FUNCIONARIOS.SALARIO
	FROM FUNCIONARIOS;
    
SELECT F.NOME, F.SALARIO, F.DT_NASCIMENTO
	FROM FUNCIONARIOS AS F;

# juntando funcionarios com departamentos
SELECT F.NOME, D.SIGLA, F.SALARIO
	FROM FUNCIONARIOS AS F, DEPARTAMENTOS AS D
    WHERE F.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
    ORDER BY F.NOME;

# fazendo a mesma junção porém usando JOINS
SELECT F.NOME, D.SIGLA
	FROM FUNCIONARIOS AS F
    INNER JOIN DEPARTAMENTOS AS D
		ON D.ID_DEPARTAMENTO = F.ID_DEPARTAMENTO
	WHERE F.GENERO = 'F'
	ORDER BY F.NOME;
    
SELECT F.NOME, T.NUMERO
	FROM FUNCIONARIOS AS F
    LEFT JOIN TELEFONES AS T
		ON T.ID_FUNCIONARIO = F.ID_FUNCIONARIO;
    
    
    
    
    
    
    
    
    
    


