USE EMPRESA;   
# RETORNE A QUANTIDADE DE FUNCIONARIOS EXISTENTE EM CADA DEPARTAMENTO
# TRAGA AO LADO DO CONTADOR O NOME DO DEPARTAMENTO   

# TOTAL  | DEPTO.
# 79     | CONTABIL
# 100    | CPD
# 93     | RH
# 109    | PES
# 88     | FINANC
# ETC.
SELECT COUNT(*) AS TOTAL, 
       D.SIGLA
	FROM FUNCIONARIOS AS F
    INNER JOIN DEPARTAMENTOS AS D
		ON F.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
    GROUP BY F.ID_DEPARTAMENTO
    ORDER BY D.SIGLA;
    
    
    
    
    
    