USE EMPRESA;

CREATE VIEW FOLHA_PAGAMENTO AS
	SELECT NOME, SALARIO
		FROM FUNCIONARIOS
        ORDER BY NOME;

SELECT * FROM FOLHA_PAGAMENTO ORDER BY SALARIO DESC;

# DROP VIEW FOLHA_PAGAMENTO;

CREATE VIEW CRUZAMENTO AS
	SELECT F.NOME, T.NUMERO, D.SIGLA
		FROM FUNCIONARIOS AS F
		INNER JOIN TELEFONES AS T
			ON F.ID_FUNCIONARIO = T.ID_FUNCIONARIO
		INNER JOIN DEPARTAMENTOS AS D
			ON F.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO;


SELECT * FROM CRUZAMENTO;   
DROP VIEW CRUZAMENTO;        

SELECT * FROM DEPARTAMENTOS; 







