USE EMPRESA;

SELECT * FROM DEPARTAMENTOS
	WHERE nome LIKE '%PTO.%';
    
DESC FUNCIONARIOS;

SELECT NOME, SALARIO
		FROM FUNCIONARIOS
        WHERE NOME LIKE '%FEIJO%';
        
SELECT NOME, SALARIO
		FROM FUNCIONARIOS
        WHERE NOME LIKE '__A%';
        
# BETWEEN - ENTRE DOIS VALORES
SELECT NOME, SALARIO 
	FROM FUNCIONARIOS
    WHERE SALARIO BETWEEN 2000 AND 3000;


SELECT NOME, SALARIO
	FROM FUNCIONARIOS
    WHERE DT_ADMISSAO BETWEEN '2011-12-10 00:03:00' AND '2015-05-18 12:30:00';
    

# IN - LISTA (CONJUNTO)
SELECT * 
	FROM DEPARTAMENTOS
    WHERE SIGLA IN ('RH', 'CPD');

SELECT ID_DEPARTAMENTO FROM DEPARTAMENTOS WHERE SIGLA = 'RH';    


SELECT NOME, SEXO, SALARIO, ID_DEPARTAMENTO
	FROM FUNCIONARIOS
	WHERE ID_DEPARTAMENTO IN (SELECT ID_DEPARTAMENTO FROM DEPARTAMENTOS WHERE SIGLA = 'FINANC');

# VERIFICAR SE UM VALOR ESTÁ VAZIO = NULO COM O NULL
SELECT NOME, SALARIO
	FROM FUNCIONARIOS
    WHERE SALARIO IS NULL;
    
# ATUALIZE OS REGISTROS SEM SALARIOS PARA O VALOR DE 2135.36 
UPDATE FUNCIONARIOS
	SET SALARIO = 2135.36
    WHERE SALARIO IS NULL;

SELECT * FROM FUNCIONARIOS WHERE SALARIO = 2135.36;

SELECT * FROM FUNCIONARIOS WHERE ID_FUNCIONARIO = 466;
SELECT * FROM FUNCIONARIOS WHERE SALARIO = 2.14;

UPDATE FUNCIONARIOS
	SET SALARIO = 2135.36
    WHERE SALARIO = 2.14;







        
        
        
        
        
    
    