USE EMPRESA;

SELECT NOME, SEXO, SALARIO
	FROM FUNCIONARIOS
    WHERE SEXO = 'F' 
          AND SALARIO >= 5000 
          AND DT_ADMISSAO BETWEEN '2010-01-01' AND '2014-01-01';

SELECT NOME, SEXO FROM FUNCIONARIOS
		WHERE SALARIO > 5000 OR NOME LIKE 'D%';
        
SELECT  nome, salario, sexo
	FROM  FUNCIONARIOS
	WHERE (nome LIKE 'A%' OR nome LIKE 'B%') AND sexo = 'M';
    
# Ordenação de registros    
# ASC => ASCENDENTE (CRESCENTE) - NAO PRECISA INFORMAR
# DESC => DESCENDENTE (DECRESCENTE)

SELECT * FROM FUNCIONARIOS
	ORDER BY SALARIO DESC;

SELECT NOME, SALARIO
	FROM FUNCIONARIOS
    WHERE SEXO = 'M'
	ORDER BY SALARIO DESC
    LIMIT 10;









    
    
    
    
    
    