CREATE DATABASE IF NOT EXISTS EMPRESA;
USE EMPRESA;

# SE QUISERMOS VER AS TABELAS DE UMA BASE 
SHOW TABLES;

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
	id_funcionario INT UNSIGNED AUTO_INCREMENT,
    nome VARCHAR(45) NOT NULL,
    genero char(1),
    dt_admissao DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_funcionario)
) ENGINE = InnoDB;

/*
# VOCE PODE TB ADICIONAR O PK NA MESMA LINHA DO ATRIBUTO ELEITO
CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
	id_funcionario INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    genero char(1),
    dt_admissao DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB;
*/




# DESCREVE A ESTRUTURA DA TABELA
DESCRIBE FUNCIONARIOS;

# POR ENQUANTO O UNICO JEITO DE ALTERAR UMA TABELA É APAGANDO E CRIANDO NOVAMENTE.
DROP TABLE FUNCIONARIOS;



# CTRL + SHIFT + ENTER (vai executar o script todo)