DROP DATABASE IF EXISTS EMPRESA;
CREATE DATABASE IF NOT EXISTS EMPRESA;
USE EMPRESA;

# CRIE A TABELA DE DEPARTAMENTOS CONFORME O DIAGRAMA APRESENTADO
CREATE TABLE IF NOT EXISTS DEPARTAMENTOS (
	id_departamento INT UNSIGNED AUTO_INCREMENT,
    sigla VARCHAR(10) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    PRIMARY KEY (id_departamento)
) ENGINE = InnoDB;

# FUNCIONARIOS
CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
	id_funcionario INT UNSIGNED AUTO_INCREMENT,
    nome VARCHAR(45) NOT NULL,
    genero char(1),
    dt_admissao DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_funcionario)
) ENGINE = InnoDB;



