USE EMPRESA;

SELECT F.NOME,
       T.NUMERO,
       D.NOME
       FROM FUNCIONARIOS AS F
       INNER JOIN TELEFONES AS T
	       ON F.ID_FUNCIONARIO = T.ID_FUNCIONARIO
	   INNER JOIN DEPARTAMENTOS AS D
           ON F.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
	ORDER BY F.NOME;
        