USE EMPRESA;

SELECT DISTINCT SEXO FROM FUNCIONARIOS;

SELECT NOME AS 'Recurso', 
       SALARIO AS 'Remuneração',
       SALARIO * 2 AS 'Salario Dobrado',
       SALARIO / 2 AS 'Metade do Salário'
       FROM FUNCIONARIOS;
       
SELECT NOME, SEXO, SALARIO 
	FROM FUNCIONARIOS
    # NO LIMIT VC PODE DEFINIR O INICIO E O TOTAL DE ITENS A SEREM TRAZIDOS
    # O LIMIT É NORMALMENTE USADO NA FUNCIONALIDADE DE PAGINAR REGISTROS NA APP
    LIMIT 0, 10;



       