USE EMPRESA;

SELECT * 
	FROM FUNCIONARIOS
    WHERE SEXO = 'F';

SELECT *
	FROM FUNCIONARIOS
    WHERE SALARIO > 5000;
    
SELECT *
	FROM FUNCIONARIOS
    WHERE DT_NASCIMENTO > '2000-01-01';
    
SELECT NOME, SALARIO
	FROM FUNCIONARIOS
    WHERE NOME = 'Daniel PETRY';
    
SELECT NOME, SALARIO
	FROM FUNCIONARIOS
    WHERE NOME LIKE 'Daniel%';
    
    