USE EMPRESA;

# CRIE UMA QUERY QUE LISTE O NOME, O SALARIO E UM BONUS DE 10% PARA CADA
# FUNCIONARIO E MOSTRE O SALARIO COM BONUS APLICADO
# LIMITANDO-SE AOS 10 PRIMEIROS REGISTROS

# Ex.
# Cicero | 1000.00 | 100.00 | 1100.00

SELECT NOME, 
       SALARIO, 
       FORMAT(SALARIO * 0.1, 2, 'de_DE') AS BONUS,
       CONCAT('R$ ', FORMAT(SALARIO * 1.1, 2, 'de_DE')) AS 'SALARIO ATUALIZADO'
	FROM FUNCIONARIOS
    LIMIT 10;
    
    