algoritmo "ex-tema-1-V2"
// Implemente um algoritmo que escreva na tela o nome da sua cidade 5 vezes
// DRY : Don´t repeat yourself (termos usados em boas praticas)

var
CONT: INTEIRO
CIDADE: CARACTER

inicio

// PRIMEIRO LEMOS A CIDADE
ESCREVAL("DIGITE A SUA CIDADE:")
LEIA(CIDADE)

LIMPATELA

ENQUANTO (CONT < 5) FACA
   ESCREVAL(CIDADE)
   
   // PRECISO INCREMENTAR 1 UNID. A CADA VOLTA
   CONT <- CONT + 1
FIMENQUANTO




fimalgoritmo
