use empresa; 
SELECT F.NOME, D.SIGLA, T.NUMERO
	FROM FUNCIONARIOS AS F
    INNER JOIN DEPARTAMENTOS AS D
		ON D.ID_DEPARTAMENTO = F.ID_DEPARTAMENTO
	INNER JOIN TELEFONES AS T
		ON F.ID_FUNCIONARIO = T.ID_FUNCIONARIO	
	ORDER BY F.NOME;
